name: Build, Save, and Tag Docker Image

on:
  push:
    tags:
      - '*'

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download GitHub CLI
      run: |
        curl -LO https://github.com/cli/cli/releases/download/v2.4.0/gh_2.4.0_linux_amd64.tar.gz
        tar -xvf gh_2.4.0_linux_amd64.tar.gz
        sudo cp gh_2.4.0_linux_amd64/bin/gh /usr/local/bin/
        gh --version  # 验证 GitHub CLI 是否成功安装

    - name: Extract tag name
      id: extract_tag
      run: |
        RELEASE_DATA=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest) && \
        TAG_NAME=$(echo $RELEASE_DATA | jq -r '.tag_name') && \
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
      
    - name: Build Docker image
      run: |
        docker build -t comfyui:${{ env.TAG_NAME }} .

    - name: Save Docker image as tar file
      run: |
        docker save -o comfyui.tar comfyui:${{ env.TAG_NAME }}

    - name: Create Release
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        gh release create ${{ env.TAG_NAME }} -t ${{ env.TAG_NAME }} -n "${{ env.TAG_NAME }} release"

    - name: Upload Release Assets
      run: |
        gh release upload ${{ env.TAG_NAME }} comfyui.tar
