name: Build, Save, and Tag Docker Image

on:
  push:
    tags:
      - '*'

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t comfyui:latest .

    - name: Save Docker image as tar file
      run: |
        docker save -o comfyui.tar comfyui:latest

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Upload Tag Artifact
      uses: actions/upload-artifact@v3
      with:
        name: comfyui-image-${{ env.TAG_NAME }}
        path: comfyui.tar
